web:
  build: .
  command: 'bash -c ''npm start'''
  working_dir: /app/user
  environment:
    PORT: 8080
  # ports:
    # - '8080:8080'
mongo:
  image: mongo
  ports:
    - "27017:27017"
  volumes_from:
    - mongodata
mongodata:
  image: tianon/true
  volumes:
    - /data/db
shell:
  build: .
  # command: bash
  # working_dir: /app/user
  environment:
    PORT: 8080
  ports:
    - '8080:8080'
  # volumes:
  #   - '.:/app/user'
